from app.models import db, Listing, environment, SCHEMA
from sqlalchemy.sql import text
# from .users import demo, alec, brad, spongebob, patrick, mr_krabs, sandy, squidward, larry, bubble_bass, man_ray


def seed_listings():
    keychron = Listing(
        owner_id=1, name='Keychron Q8 Alice Layout', price=250, description="The Keychron Q8 is a compact, wireless mechanical keyboard designed for both Mac and Windows users. It features a tenkeyless layout, meaning that it doesn't have a numeric keypad, allowing for a more compact design that saves desk space. The keyboard has a sleek, minimalist design with a black aluminum frame and white LED backlighting that enhances the readability of the keys. The Q8 features high-quality Gateron mechanical switches that offer a satisfying tactile feedback and a reliable lifespan of up to 50 million keystrokes. It also comes with a choice of different switch options, including Blue, Red, Brown, and White switches, allowing users to customize their typing experience to their preferences. The keyboard is compatible with Bluetooth 5.1 and can connect up to three devices simultaneously, making it easy to switch between multiple devices with just a press of a button. It also features a USB-C port for charging, which provides up to 240 hours of battery life on a single charge, depending on usage. The Q8 also comes with various additional features, including a built-in keycap puller for easy maintenance and a variety of media and function keys that make it easy to control media playback, adjust volume, and access other useful functions quickly. Overall, the Keychron Q8 is a versatile, high-quality mechanical keyboard that combines a compact design, wireless connectivity, and customizable features to provide a comfortable and efficient typing experience.")

    uhk = Listing(
        owner_id=1, name='Ultimate Hacking Keyboard', price=325, description='The UHK is a compact, 66-key mechanical keyboard that is designed to provide a high-quality typing experience in a small form factor. The keyboard has a sleek, modern design with a black aluminum frame and white LED backlighting that enhances the readability of the keys. The PC 66 features high-quality Cherry MX mechanical switches that offer a satisfying tactile feedback and a reliable lifespan of up to 50 million keystrokes. It also comes with a choice of different switch options, including Red, Blue, Brown, and Clear switches, allowing users to customize their typing experience to their preferences.The keyboard is fully programmable with onboard memory, which allows users to customize the key layout and programming without the need for external software. It also features a dual-layer PCB for added durability and a detachable USB cable for easy transport. Overall, the Vortex PC 66 is a versatile, high-quality mechanical keyboard that combines a compact design, customizable features, and durable construction to provide a comfortable and efficient typing experience.')

    coffee = Listing(
        owner_id=1, name='Ultimate Hacking Keyboard Coffee', price=500, description="The Ultimate Hacking Keyboard (UHK) is a powerful and customizable keyboard that is designed for programmers and other professionals who demand precision and efficiency. The UHK is known for its modular design, ergonomic layout, and advanced features, and it is now available in a coffee-themed aesthetic that is sure to please coffee lovers and caffeine aficionados alike. The coffee-themed UHK features a sleek and stylish design that is inspired by the rich and complex flavors of coffee. The keyboard's body is a warm brown color that is reminiscent of freshly roasted coffee beans, and its keys are a rich cream color that evokes the creamy foam of a latte or cappuccino. The UHK's coffee-themed aesthetic is more than just a stylish design choice, however. It also reflects the keyboard's commitment to efficiency and productivity, just like a good cup of coffee. The UHK's ergonomic layout is designed to reduce strain on the hands and wrists, allowing users to type comfortably for longer periods of time. The keyboard's modular design also allows users to customize it to suit their specific needs, so they can work more efficiently and effectively. In addition to its ergonomic and customizable design, the coffee-themed UHK also boasts a range of advanced features that make it the ultimate tool for hacking and programming. The keyboard features a split design that allows users to adjust the angle and position of the two halves for maximum comfort and efficiency. It also has fully programmable keys, so users can create custom macros and shortcuts that streamline their workflow. Overall, the coffee-themed Ultimate Hacking Keyboard is a stylish and powerful tool that is perfect for anyone who demands precision, efficiency, and a good cup of coffee. With its ergonomic design, customizable layout, and advanced features, it is sure to become the go-to keyboard for programmers, developers, and coffee lovers everywhere.")

    varmilo = Listing(
        owner_id=1, name='Varmilo Miya Summit Pro', price=200, description="The Varmilo Miya Summit Pro Mechanical Keyboard is a high-quality, customizable keyboard that is designed to meet the demands of serious gamers and professional typists alike. This keyboard features a sleek, compact design that is perfect for use in small spaces, while still providing all the functionality and performance that you need. The Varmilo Miya Summit Pro Mechanical Keyboard features a full set of 108 mechanical keys, each with a Cherry MX switch that provides a tactile and responsive typing experience. The switches are available in a variety of different types, including red, brown, blue, and silver, so you can choose the one that best suits your needs. One of the standout features of this keyboard is its customizable LED backlighting. You can choose from a wide range of different colors and lighting patterns, allowing you to create a personalized look that reflects your own style and preferences. The keyboard also features a number of other customizable features, such as macro programming and key remapping, which allow you to optimize your workflow and increase your productivity. The Varmilo Miya Summit Pro Mechanical Keyboard also features a number of ergonomic design elements that make it comfortable to use for extended periods of time. The keyboard has a slight angle that places your hands in a more natural position, and the keycaps are sculpted to provide a more comfortable typing experience. The keyboard also includes a detachable USB cable, making it easy to transport and store. Overall, the Varmilo Miya Summit Pro Mechanical Keyboard is an excellent choice for anyone who is looking for a high-quality, customizable keyboard that provides both style and performance. With its compact design, customizable LED backlighting, and ergonomic features, this keyboard is a great option for gamers, typists, and anyone else who demands the best in their computing accessories.")

    q65 = Listing(
        owner_id=1, name='Keychron Q65', price=225, description="The Keychron Q65 Mechanical Keyboard is a compact and portable keyboard that is designed for ultimate typing efficiency. This keyboard features a compact 65% layout, which means that it has all the keys you need for efficient typing, but without taking up too much space on your desk. It is a great choice for those who want a high-quality keyboard that is easy to carry around. The Keychron Q65 Mechanical Keyboard features hot-swappable mechanical switches, which means that you can easily change out the switches without having to desolder them. This allows you to easily customize your typing experience and switch between different switch types without any hassle. The keyboard supports both Cherry and Gateron switches, and is also compatible with other 3-pin mechanical switches. Another standout feature of the Keychron Q65 Mechanical Keyboard is its Bluetooth connectivity. The keyboard can be paired with up to three devices, making it easy to switch between different devices with the touch of a button. It also has a wired USB-C connection for those who prefer a wired connection. The Keychron Q65 Mechanical Keyboard also has a variety of customizable features, including a programmable layout and RGB backlighting. You can use the included software to customize the layout of the keys and create custom macros, allowing you to optimize your workflow and increase your productivity. The RGB backlighting allows you to choose from a wide range of different colors and lighting effects, so you can create a personalized look that suits your style. Overall, the Keychron Q65 Mechanical Keyboard is a great choice for those who want a compact, customizable, and portable keyboard that is easy to use and provides ultimate typing efficiency. With its hot-swappable mechanical switches, Bluetooth connectivity, and customizable features, this keyboard is a great option for gamers, typists, and anyone else who wants a high-quality keyboard that is both efficient and stylish.")

    q65mars = Listing(
        owner_id=1, name='Keychron Q65 Mars', price=315, description="The Keychron Q65 Mechanical Keyboard is a high-quality and customizable keyboard that is perfect for anyone who demands efficiency and performance. And now, with its stunning space-themed aesthetic, it's also perfect for anyone who loves the cosmos and all things celestial. The Keychron Q65 Mechanical Keyboard's space-themed design is a beautiful blend of deep blacks, vivid blues, and glistening silver accents. The black body of the keyboard is reminiscent of the infinite void of space, while the silver accents represent the stars and other celestial objects that glitter in the night sky. The vivid blue LED backlighting adds a pop of color that looks like a star-filled galaxy. This keyboard features a compact 65% layout that maximizes efficiency while taking up minimal space on your desk. It also has hot-swappable mechanical switches, which means you can customize your typing experience by easily switching out the switches without the need for desoldering. The Keychron Q65 is compatible with Cherry and Gateron switches, as well as other 3-pin mechanical switches. The Keychron Q65 Mechanical Keyboard's wireless Bluetooth connectivity allows you to pair up to three devices, making it easy to switch between different devices with just a touch of a button. It also has a wired USB-C connection for those who prefer a wired setup. This keyboard features customizable RGB backlighting that allows you to choose from a wide range of colors and lighting effects to create a personalized look that suits your style. The keyboard's customizable features also include a programmable layout, allowing you to create custom macros and optimize your workflow for maximum productivity. Overall, the Keychron Q65 Mechanical Keyboard with its stunning space-themed aesthetic, hot-swappable switches, wireless connectivity, and customizable features is an excellent choice for anyone who wants a high-quality keyboard that is efficient, stylish, and out of this world.")

    pc66 = Listing(
        owner_id=1, name='Vortex PC66 Gray', price=175, description="The Vortex PC66 Mechanical Keyboard is a compact and portable keyboard that offers exceptional typing performance. It features a 66-key layout that includes all the essential keys for efficient typing, while still being small enough to fit into tight spaces. The keyboard is built with a sturdy aluminum frame that provides excellent durability and a premium feel. It also has a detachable USB-C cable for easy portability and maintenance. The PC66 uses Cherry MX switches, which are known for their tactile feedback and durability. You can choose from a variety of switch types, including Red, Blue, Brown, Silver, and Clear, depending on your preference. The keyboard also features customizable RGB backlighting, which allows you to choose from a wide range of colors and lighting effects. You can use the included software to program macros and remap keys for even greater customization. Overall, the Vortex PC66 Mechanical Keyboard is a great choice for anyone who values performance, durability, and portability in a compact form factor.")

    pc66white = Listing(
        owner_id=1, name='Vortex PC66', price=175, description="The Vortex PC66 Mechanical Keyboard is a compact and portable keyboard that offers exceptional typing performance. It features a 66-key layout that includes all the essential keys for efficient typing, while still being small enough to fit into tight spaces. The keyboard is built with a sturdy aluminum frame that provides excellent durability and a premium feel. It also has a detachable USB-C cable for easy portability and maintenance. The PC66 uses Cherry MX switches, which are known for their tactile feedback and durability. You can choose from a variety of switch types, including Red, Blue, Brown, Silver, and Clear, depending on your preference. The keyboard also features customizable RGB backlighting, which allows you to choose from a wide range of colors and lighting effects. You can use the included software to program macros and remap keys for even greater customization. Overall, the Vortex PC66 Mechanical Keyboard is a great choice for anyone who values performance, durability, and portability in a compact form factor.")

    unicomp = Listing(
        owner_id=1, name='Unicomp Model M', price=135, description="The Unicomp Model M Mechanical Keyboard is a vintage-inspired keyboard that pays homage to the iconic IBM Model M keyboard from the 1980s. It boasts a rugged and durable construction, with buckling spring switches that provide a tactile and audible feedback for each keypress. Its retro-style layout features a numpad and function keys, making it versatile enough for a wide range of applications. The keyboard's curved key design and built-in wrist rest offer a comfortable and ergonomic typing experience, while its laser-etched keys ensure long-lasting durability. The Unicomp Model M also has customizable features, such as programmable function keys and macro support, to increase productivity and streamline workflow. Despite its vintage design, the keyboard is compatible with modern operating systems and has a USB interface that is plug-and-play compatible with Windows, Mac, and Linux. The Unicomp Model M Mechanical Keyboard is the perfect choice for anyone who wants a reliable and sturdy keyboard with a unique vintage style that is built to last.")

    commodore = Listing(
        owner_id=1, name='Commodore 64', price=375, description="The Commodore 64 Keyboard is a vintage computer keyboard that was released in 1982 by Commodore International. It was the primary input device for the Commodore 64, which was one of the most popular home computers of the 1980s. The keyboard has a distinctive look and feel, with its cream-colored keys and blue function keys. The key switches are made of a tactile and clicky mechanical design, which provides a satisfying and audible feedback with every keystroke. The keyboard layout includes a standard QWERTY layout with a dedicated numeric keypad, function keys, and arrow keys, as well as a variety of special characters and symbols. Despite its age, the Commodore 64 Keyboard remains a popular choice for retro computing enthusiasts and collectors. Many people appreciate the keyboard's classic design and nostalgic appeal, and some even use it to develop and play vintage games and software. The keyboard has a sturdy and durable construction, with keys that are resistant to wear and tear. Additionally, the keyboard is compatible with modern systems via USB adapters, allowing it to be used with modern computers and emulators. In summary, the Commodore 64 Keyboard is a classic and iconic input device that played a significant role in the rise of home computing. Its mechanical key switches, comfortable layout, and powerful features made it a favorite among early computer users. Today, it remains a beloved collector's item and a testament to the enduring appeal of vintage technology.")


    db.session.add(keychron)
    db.session.add(uhk)
    db.session.add(coffee)
    db.session.add(varmilo)
    db.session.add(q65)
    db.session.add(q65mars)
    db.session.add(pc66)
    db.session.add(pc66white)
    db.session.add(unicomp)
    db.session.add(commodore)

    db.session.commit()


def undo_listings():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.listings RESTART IDENTITY CASCADE;")

    else:
        db.session.execute(text("DELETE FROM listings"))

    db.session.commit()
